[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_blog = "CMF1K4xXdEFzz7G3V7y2KW4uBfnT7u2sXn9RBq99qgGq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ""

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
